# Use the official Node.js image based on Alpine Linux
FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /var/sw/johnsonchan/frontend

# Copy the package.json file to the working directory
COPY package.json ./

# Install the dependencies specified in package.json
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Command to run the application
CMD ["npm", "run", "start"]